<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Aspire.Azure.Messaging.ServiceBus" />
    <PackageReference Include="Aspire.Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EventFanout.ServiceDefaults\EventFanout.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Shared.Events\Shared.Events.csproj" />
  </ItemGroup>

</Project>
